require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');

const products = [
    { name: "Cyber Jacket 2077", price: "$299", rating: 4.9, image: "/images/hero-wear-jacket.png", tag: "Best Seller", category: "Fashion", description: "Nanofiber weave with programmable LED accents. Weather-resistant and EMP-hardened.", stock: 12, specs: ["Material: Graphene-Cotton Blend", "Weight: 1.2kg", "Battery: 48h LED Life"], reviews: 128, colors: ["#000000", "#1a1a1a", "#002244"], lore: "Originally designed for the street samurai of Neo-Tokyo, this jacket offers Class-III ballistic protection without compromising style. The interwoven fibers react to urban pollution, changing hue to warn the wearer of toxins." },
    { name: "Neural Link V2", price: "$599", rating: 5.0, image: "/images/hero-headphone.png", tag: "New Arrival", category: "Tech", description: "Direct brain-computer interface. Stream music and data directly to your cortex.", stock: 5, specs: ["Latency: <1ms", "Bandwidth: 100Tbps", "Compatibility: Cortex v4.0+"], reviews: 45, colors: ["#ffffff", "#ff00ff", "#00ffff"], lore: "Bypass your ears entirely. The V2 uses resonance waves to stimulating the auditory cortex directly, providing fidelity that exceeds biological limits." },
    { name: "Gravity Sneakers", price: "$189", rating: 4.7, image: "/images/hero-wear-sneaker.png", tag: "Limited", category: "Fashion", description: "Anti-gravity soles allow for higher jumps and reduced fall damage.", stock: 3, specs: ["Thrust: 5N", "Cushion: Quantum Foam", "Size: Auto-Lacing"], reviews: 89, colors: ["#ff4500", "#000000", "#ffffff"], lore: "Banned in three professional sports leagues, Gravity Sneakers use localized graviton fields to reduce user weight by 40% during vertical acceleration." },
    { name: "Quantum Watch", price: "$349", rating: 4.8, image: "/images/hero-smartwatch.png", tag: "Trending", category: "Tech", description: "Synchronizes with atomic time servers. Includes holographic projector.", stock: 20, specs: ["Display: 3D Holo", "Battery: Nuclear Cell (10y)", "Waterproof: 500m"], reviews: 230, colors: ["#silver", "#gold", "#black"], lore: "Never lose a second. This timepiece is entangled with the Atomic Prime Server in Zurich, ensuring accuracy to the picosecond." },
    { name: "Holo-Visor X1", price: "$499", rating: 4.9, image: "/images/hero-vr.png", tag: "Exclusive", category: "Gaming", description: "Full AR/VR overlay capability with top-tier refresh rates.", stock: 8, specs: ["FOV: 210°", "Refresh: 240Hz", "Resolution: 16K per eye"], reviews: 67, colors: ["#111111", "#00ff00"], lore: "See the world as it truly is—or how you want it to be. The X1 overlays critical data, navigation, and threat assessment in real-time." },
    { name: "Stealth Drone", price: "$899", rating: 4.9, image: "/images/feature-rocket.png", tag: "Tech", category: "Tech", description: "Silent propulsion stealth drone with 8K reconnaissance camera.", stock: 15, specs: ["Range: 50km", "Noise: <10dB", "Speed: Mach 0.5"], reviews: 12, colors: ["#333333"], lore: "The preferred reconnaissance tool of corporate spies. Its silent ion drive makes it virtually undetectable by standard audio sensors." },
    { name: "Bio-Shield Pack", price: "$129", rating: 4.6, image: "/images/feature-shield.png", tag: "Protection", category: "Protection", description: "Personal energy shield generator. Blocks minor projectiles and debris.", stock: 42, specs: ["Capacity: 5000J", "Recharge: Solar/Kinetic", "Weight: 0.5kg"], reviews: 341, colors: ["#0000ff", "#ff0000"], lore: "Standard issue for asteroid miners, this emitter creates a localized kinetic barrier capable of stopping micrometeorites and stray bolts." },
    { name: "AI Assistant Core", price: "$999", rating: 5.0, image: "/images/feature-support.png", tag: "Software", category: "Tech", description: "Level 5 AI personality core. Capable of managing all smart home devices.", stock: 2, specs: ["IQ: 450", "Empathy: Adjustable", "Security: Quantum Encryption"], reviews: 9, colors: ["#ffffff"], lore: "More than just software, the Core learns your habits, predicts your needs, and can simulate human conversation with 99.9% accuracy." },
    { name: "Holo-Console X", price: "$799", rating: 4.8, image: "/images/cat-gaming.png", tag: "Gaming", category: "Gaming", description: "Next-gen gaming unit with 120TF processing power and holographic display.", stock: 7, specs: ["GPU: Photon Core", "Storage: 10PB DNA Drive", "Output: Direct Retinal"], reviews: 156, colors: ["#000000"], lore: "The console that ended the 'console wars'. With infinite cloud processing and holographic rendering, the screen is no longer the limit." },
    { name: "Void Silk Dress", price: "$450", rating: 4.7, image: "/images/cat-fashion.png", tag: "Fashion", category: "Fashion", description: "Made from genetically modified silk worms. Changes color based on mood.", stock: 6, specs: ["Fabric: Bio-Silk", "Tech: Mood Sensors", "Wash: Self-Cleaning"], reviews: 42, colors: ["#1a1a1a", "#4b0082"], lore: "Woven from the silk of lunar moths, this fabric binds to the wearer's biosignature, shifting color and opacity to match their emotional state." },
    { name: "Levitation Boots", price: "$320", rating: 4.9, image: "/images/cat-shoes.png", tag: "Footwear", category: "Fashion", description: "Industrial grade levitation thrusters. Flight time: 2 hours.", stock: 9, specs: ["Lift: 150kg", "Fuel: Hydrogen Cells", "Safety: Auto-Land"], reviews: 78, colors: ["#808080", "#000000"], lore: "Walk on air. Literally. These boots use micro-thrusters to provide active lift, making every step feel like walking on the moon." },
    { name: "Smart Shades", price: "$199", rating: 4.5, image: "/images/cat-accessories.png", tag: "Wearable", category: "Fashion", description: "Heads-up display sunglasses. Filters UV and translates text instantly.", stock: 25, specs: ["Lens: Smart Glass", "Conn: 6G", "Weight: 25g"], reviews: 560, colors: ["#000000", "#ffeb3b"], lore: "Don't just look—see. Instant translation, facial recognition, and route guidance, all projected onto a stylish polarized lens." },
    { name: "Quantum Chipset", price: "$1200", rating: 5.0, image: "/images/cat-electronics.png", tag: "Hardware", category: "Tech", description: "The fastest consumer processor on the market. Quantum entangled cores.", stock: 4, specs: ["Clock: 500GHz", "Cores: 1024 Qubit", "TDP: 5W"], reviews: 3, colors: ["#ffd700"], lore: "Processing power that bends reality. By utilizing quantum superposition, this chipset can calculate every possible outcome of a game frame simultaneously." },
    { name: "Golden Cyber Jacket", price: "$9999", rating: 5.0, image: "/images/deal-exclusive.png", tag: "Legendary", category: "Fashion", description: "One of a kind. Gold-plated weave with diamond-encrusted interface ports.", stock: 1, specs: ["Material: 24K Gold / Kevlar", "Gems: 50ct Diamonds", "Armor: Class 4"], reviews: 1, colors: ["#ffd700"], lore: "The ultimate status symbol. Commissioned by the CEO of NanoTech, this jacket is as much a piece of art as it is functional armor." },
    { name: "Plasma Katana", price: "$850", rating: 4.9, image: "/images/feature-rocket.png", tag: "Weapon", category: "Protection", description: "High-frequency blade capable of cutting through molecular bonds.", stock: 3, specs: ["Temp: 5000K", "Length: 105cm", "Handle: Polymer Grip"], reviews: 22, colors: ["#ff0000", "#00ff00", "#0000ff"], lore: "A modern reimagining of an ancient weapon. The edge vibrates at 50,000Hz, allowing it to part steel as easily as silk." },
    { name: "Neon Street Bike", price: "$15000", rating: 5.0, image: "/images/cat-gaming.png", tag: "Vehicle", category: "Tech", description: "Electric superbike with hubless wheels and auto-pilot navigation.", stock: 1, specs: ["Top Speed: 300km/h", "Range: 500km", "AI: Co-Pilot V3"], reviews: 5, colors: ["#00ffff", "#ff00ff"], lore: "Tear through the neon-soaked streets in silence. The magnetic hubless wheels provide zero friction for maximum acceleration." },
    { name: "Cyber-Pet Dog", price: "$2200", rating: 4.6, image: "/images/cat-accessories.png", tag: "Companion", category: "Tech", description: "Robotic canine with realistic behavior and home defense protocols.", stock: 8, specs: ["Material: Titanium Alloy", "Battery: 1 Week", "Commands: 500+"], reviews: 40, colors: ["#c0c0c0"], lore: "Man's best friend, upgraded. Loyal, brave, and equipped with a stun-baton in its tail. No feeding required." },
    { name: "Holo-Projector 9000", price: "$650", rating: 4.4, image: "/images/hero-vr.png", tag: "Home", category: "Tech", description: "Transforms any room into an immersive 3D environment.", stock: 18, specs: ["Res: 8K 360°", "Sound: Spatial Audio", "Input: Gesture"], reviews: 88, colors: ["#ffffff", "#000000"], lore: "Why leave home when you can bring the world to you? The 9000 series turns your living room into a forest, a beach, or deep space." },
    { name: "Tactical Exosuit", price: "$4500", rating: 4.8, image: "/images/hero-wear-jacket.png", tag: "Military", category: "Protection", description: "Enhances strength and agility. Bulletproof and fire-resistant.", stock: 2, specs: ["Strength: +500%", "Armor: Class 5", "Weight: 15kg"], reviews: 14, colors: ["#2f4f4f", "#000000"], lore: "Become a one-man army. The hydraulics in this suit allow the wearer to lift a car, while the ceramic plating can stop a tank round." },
    { name: "Neural Implant Kit", price: "$300", rating: 4.2, image: "/images/hero-smartwatch.png", tag: "DIY", category: "Tech", description: "Do-it-yourself memory expansion kit. installation requires medical license.", stock: 50, specs: ["Capacity: 1PB", "Interface: Wetware", "Risk: Moderate"], reviews: 12, colors: ["#ff0000"], lore: "Running out of headspace? This kit splices an additional petabyte of storage directly into your hippocampus. Side effects may include recurring dreams of electric sheep." },
    { name: "Zero-G Backpack", price: "$150", rating: 4.7, image: "/images/feature-shield.png", tag: "Travel", category: "Fashion", description: "Reduces the effective weight of contents by 90% using gravity fields.", stock: 10, specs: ["Volume: 40L", "Battery: 24h", "Fabric: Ripstop"], reviews: 205, colors: ["#808080", "#000000", "#0000ff"], lore: "Carry the world on your shoulders without feeling a thing. The internal gravity dampeners make 50kg feel like 5kg." },
    { name: "Chameleon Skin Suit", price: "$750", rating: 4.5, image: "/images/cat-fashion.png", tag: "Stealth", category: "Fashion", description: "Full body suit that mimics surrounding textures for active camouflage.", stock: 5, specs: ["Adaption: 0.1s", "Texture: Real-Feel", "Power: Kinetic"], reviews: 33, colors: ["#000000"], lore: "The ultimate in urban camouflage. Whether you're hiding from authorities or just avoiding an awkward conversation, the Skin Suit has you covered." },
    { name: "Plasma Rifle Replica", price: "$120", rating: 4.3, image: "/images/cat-electronics.png", tag: "Prop", category: "Gaming", description: "High-quality replica from popular game. Non-functional, display only.", stock: 100, specs: ["Scale: 1:1", "Lights: RGB", "Material: Resin"], reviews: 56, colors: ["#ffffff", "#000000"], lore: "A perfect 1:1 scale model of the legendary BFG-9000. It won't blast a hole in Mars, but it looks great on a shelf." },
    { name: "Cyber-Goggles", price: "$80", rating: 4.1, image: "/images/hero-vr.png", tag: "Entry", category: "Fashion", description: "Fashionable eyewear with basic AR notifications and navigation.", stock: 60, specs: ["OS: GlassOS Lite", "Battery: 12h", "Style: Retro"], reviews: 412, colors: ["#ff69b4", "#00ffff"], lore: "Retro style meets modern tech. Get your notifications delivered right to your peripheral vision without looking like a cyborg." }
];

mongoose.connect(process.env.MONGO_URI)
    .then(async () => {
        console.log('MongoDB Connected');
        console.log('Clearing old products...');
        await Product.deleteMany({});
        console.log(`Seeding ${products.length} products...`);
        await Product.insertMany(products);
        console.log('Data Upload Complete!');
        process.exit();
    })
    .catch(err => {
        console.error('Seeding Failed:', err);
        process.exit(1);
    });
